### ISSUE TITLE
I'm facing issues with the file upload block after version 2.16. 

### ISSUE THREAD

**Issue by GFBeck** [baptisteArno/typebot.io#1020]
![WhatsApp Image 2023-11-09 at 00 15 52](https://github.com/baptisteArno/typebot.io/assets/87678803/3ec6c872-fd67-4301-94ad-fd362bf1b01d)

I use AWS S3 integration, and everything was fine until 2.16. However, after that, when trying to upload, it gives the error "An error occurred while uploading the file." 

Can someone help me with this issue?

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by amitshuklabag** [comment]
I've encountered a similar problem when dealing with uploads of files, images, and other media types. 

I configured s3 endpoints in the docker-compose environment other than 127.0.0.1, but it seems that the issue persists because in the backend it was connecting with 127.0.0.1, indicating that it is not utilizing the specified endpoints.

![image](https://github.com/baptisteArno/typebot.io/assets/53058928/63cea58a-1d37-4c16-acb7-da118d08c4d2)

**Comment by JGz4PS8DfvVb53** [comment]
I have the same issue. Does somebody have an idea how it could be solved?
![image](https://github.com/baptisteArno/typebot.io/assets/64353364/783d5a7a-9622-4b79-8c79-3b445ab7c56a)

**Comment by baptisteArno** [comment]
Closing it. Feel free to re-open if you have more info 🙏
