### ISSUE TITLE
The API developer key is invalid.

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#1163]
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/6ab56f7f-1121-4287-be4d-f7677ef79ff7)
This just started to pop up I was not having any issues. May be related to cloudron but im not sure its such an odd error. Nothing in the logs.

**Comment by CptPlastic** [comment]
https://discord.com/channels/1155799591220953138/1197312390144987156

**Comment by CptPlastic** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/fcbd05fb-8956-4b29-b009-68c28a818466)
It also is looking strange not like the established blocks look that still work.

**Comment by patrickluizdev** [comment]
I also have this problem "The API developer key is invalid."

**Comment by baptisteArno** [comment]
Now the Google Sheets block uses the Drive Picker API to be more compliant with privacy
See the breaking changes here: https://github.com/baptisteArno/typebot.io/releases/tag/v2.21.0

**Comment by CptPlastic** [comment]
> I also have this problem "The API developer key is invalid." solution, I ran the v2.20.0 image

make sure you add and enable the "google picker api"

![image](https://github.com/baptisteArno/typebot.io/assets/1010444/cee1e502-5d28-40a7-a128-def0aa28008c)

**Comment by WilliamAlmeida** [comment]
To troubleshoot the issue with the developerKey not being sent when viewing sheets in Typebot Viewer (v2.28), here are some key points to consider:

OAuth Authentication Success: You mentioned that the OAuth authentication is working fine, which means the initial handshake with the API is successful.

Missing developerKey: The developerKey is not being included in the request when you attempt to view the sheets. This is likely why you're not able to see the sheets unless you manually add the key.

Manual Intervention Works: When you manually navigate to the URL and include the developerKey, the sheets are listed correctly. This indicates that the issue is specific to the way the key is being handled or transmitted by the Typebot Viewer.

developerKey (empty)
![google sheet error developer key empty](https://github.com/user-attachments/assets/4022260a-a7fc-40f4-be82-2fee1a263a53)

developerKey (filled)
![google sheet error developer key filled](https://github.com/user-attachments/assets/2bf9e749-caae-4bc1-abe9-90ce5e87d46a)

**Comment by m4ary** [comment]
> To troubleshoot the issue with the developerKey not being sent when viewing sheets in Typebot Viewer (v2.28), here are some key points to consider:
> 
> OAuth Authentication Success: You mentioned that the OAuth authentication is working fine, which means the initial handshake with the API is successful.
> 
> Missing developerKey: The developerKey is not being included in the request when you attempt to view the sheets. This is likely why you're not able to see the sheets unless you manually add the key.
> 
> Manual Intervention Works: When you manually navigate to the URL and include the developerKey, the sheets are listed correctly. This indicates that the issue is specific to the way the key is being handled or transmitted by the Typebot Viewer.
> 
> developerKey (empty) ![google sheet error developer key empty](https://private-user-images.githubusercontent.com/5334396/367148199-4022260a-a7fc-40f4-be82-2fee1a263a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDQxMDEsIm5iZiI6MTczMDg0MzgwMSwicGF0aCI6Ii81MzM0Mzk2LzM2NzE0ODE5OS00MDIyMjYwYS1hN2ZjLTQwZjQtYmU4Mi0yZmVlMWEyNjNhNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMjE1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM2MWU1OGZhYzhlMmJlMzkxYjI5ZTllNzZhNGNiYWM2YjRkMDY0YjY5YTliOThjZjI0OTM5NmVmYTEwMjBhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.alqAqKqcPzk-qd5S3DsbLub-D2Bgai03bCnUK0GJ5Zc)
> 
> developerKey (filled) ![google sheet error developer key filled](https://private-user-images.githubusercontent.com/5334396/367149125-2bf9e749-caae-4bc1-abe9-90ce5e87d46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDQxMDEsIm5iZiI6MTczMDg0MzgwMSwicGF0aCI6Ii81MzM0Mzk2LzM2NzE0OTEyNS0yYmY5ZTc0OS1jYWFlLTRiYzEtYWJlOS05MGNlNWU4N2Q0NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMjE1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM2Mjk0MDRhYmM5YzEwZmZiYzJiYWFlZDk3YThlOTE1NDI5NGRkNzE0NDc1ODc5YjMyN2JkZWE4ZTE1OWZlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g7rsxJTR1TE6nhTyz9QFN1JYclTGYCn2OYxwz4wZht8)

i have same problem as you `developerKey` is undefined, is their a fix for it ?
