### ISSUE TITLE
RequestError: self-signed certificate"

### ISSUE THREAD

**Issue by Dorpoa** [baptisteArno/typebot.io#1477]
Hello!
I would like your help to resolve a problem that is happening.

My system works normally for a few minutes and then stops and displays the following error:

   "response":{   
     "statusCode": 500,
     "date": {"message": "Error from Typebot server: RequestError: self-signed certificate"   }
   }

How can I resolve this? I'm using a certificate created by win-acme

**Comment by baptisteArno** [comment]
Where do you see that issue?

**Comment by Dorpoa** [comment]
On my server...
when I run the flow test..

It has the latest version, and everything works again if I restart the Server. Problem that stops working again after a few hours.

**Comment by baptisteArno** [comment]
I'm not aware of anything that could cause that kind of issue 🤔

What do you mean by saying that your system "stops"?

I'm sorry but that issue is lacking a lot of context and information. Please try to provide as much info as possible such as clear server logs, video recording etc..

Feel free to re-open when you have all that info 🙏
