### ISSUE TITLE
ElevenLabs blocks dont work

### ISSUE THREAD

**Issue by atadeu** [baptisteArno/typebot.io#1573]
After configurate elevenlabs block correctly, and save url to a var, put it in a audio block and wait to work. But dont, flow or ignore ou pause to wait and get a long time to responde and dont get a response in elevenlabs block and audio block.

Consulting Elevenlabs and all requisition in elevenlabs block has executed in elevenlabs.

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

Also did you make sure to configure a S3? Elevenlabs can't work without it. https://docs.typebot.io/self-hosting/configuration#s3-storage-media-uploads

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
