### ISSUE TITLE
Set variable in API

### ISSUE THREAD

**Issue by Tint0ri** [baptisteArno/typebot.io#1691]
is it possible to set bot internal variable with startChat and continueChat API?  I want start a typebot with a location information and update the location during the whole session. I can get location information from client by external code, but I cannot send the location information into session during API call.

**Comment by leo-alvarenga** [comment]
This. This feature would greatly improve our ability to create much more dynamic bots, especially if it could come as a new endpoint entirely.

For instance, in my use case, I am running multiple specialized bots for customer support via WhatsApp by leveraging [EvolutionAPI's](https://github.com/EvolutionAPI/evolution-api) Typebot integrations. 

Thing is, this API only supports integration with a single bot. In the current use case I'm working on, I've managed to get around this so far by using the `Typebot` block and redirecting the user to different bots as needed. For obvious reasons, it would make a lot of sense to control to which bot the user should be redirect to based on the assessment of the support specialist. Since that I already have all the info about the bot and its session, I should the bot session as I wish

**Comment by GabrielBragaGit** [comment]
While I may not fully understand your specific needs, I'd like to suggest an approach I use for passing information in Typebot API requests. Within the 'startParams' object, you can set the value of 'prefilledVariables' with any variables you desire. If necessary, you can perform logical checks in your flow with this information to route the conversation accordingly. Additionally, if it suits your requirements, you can use an external table or spreadsheet to save location data based on session or ID.

**Comment by baptisteArno** [comment]
I think if you ever feel the need to internally update a variable using another API call, you are building it wrong with Typebot.

You should be able to have a set variable logic directly on Typebot. Just add a Set variable block with the "Execute on client" option and then you trigger the code on your client and send back the answer to set that variable.

Does that make sense?

**Comment by Tint0ri** [comment]
Thanks.
