### ISSUE TITLE
Typebot error using nocodb, when searching for the first row with empty or zero data

### ISSUE THREAD

**Issue by BrunoFernandesDev** [baptisteArno/typebot.io#1798]
When using the nocodb integration in typebot, if the first record of the table in nocodb is empty or the column is a number and has the value zero, typebot gives an error, informing that the column does not exist, this only happens if it is the first record of the table in nocodb

In this image I show how my first record is. I need to get all the records in the table. My problem is in this column called "estoque" which is zero. Typebot gives an error when returning the data because of this column.
![Captura de tela de 2024-09-17 20-08-52](https://github.com/user-attachments/assets/1cf3a8ad-84a3-455c-a201-359c200cb644)

Below I show how my typebot is.
![Captura de tela de 2024-09-17 20-09-49](https://github.com/user-attachments/assets/21480bdc-342f-454b-80f9-3840306957a1)

This is the error I have when searching for the data
![Captura de tela de 2024-09-17 20-13-57](https://github.com/user-attachments/assets/bab6afb2-5f85-4849-a18f-79a015796a2c)

Sorry for my English

**Comment by neehhaa06** [comment]
Hello @BrunoFernandesDev :)

fix: #1798

`
Please , To resolve the Typebot error when fetching records with an empty or zero "estoque" field from NocoDB, modify your Typebot workflow to handle null or zero values by adding a fallback, like a default value (e.g., "Not Available") for the "estoque" field. Alternatively, in NocoDB, set a default value in the "estoque" column schema to avoid null entries. You can also adjust your query to exclude rows with null or zero values. Implement error handling in Typebot to log and skip problematic rows instead of halting the entire process.
`
