### ISSUE TITLE
It would be possible to add the arrow within the groups

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#219]
I don't know if it describes it correctly but this is what I mean:
![image](https://user-images.githubusercontent.com/52453013/210998172-30bd1ddb-7da8-4f53-9b5e-2632152f5a9f.png)

**Comment by Jorgelig** [comment]
The flow is between groups, it seems to me that it is clearer for the user that the arrow points to the group and not some component within the group

**Comment by baptisteArno** [comment]
> The flow is between groups, it seems to me that it is clearer for the user that the arrow points to the group and not some component within the group

You can also connect an arrow to a specific block inside a group, so that's a legit improvement

**Comment by Jorgelig** [comment]
I tried with several blocks but I couldn't connect directly, how can I replicate that scenario?

![Image](https://user-images.githubusercontent.com/581672/212826419-a0266c88-3f3d-4ea5-8652-91f760be3fae.png)

**Comment by baptisteArno** [comment]
This one is a bit complicated @Jorgelig for now. I'll need to check it out myself!

**Comment by baptisteArno** [comment]
I decided not to implement this because it would imply more computation on each graph render.
Typebot already struggles performance-wise with large flows. I can't afford more computation for a minor cosmetic change.

However, figured there's a misalignment when the edge is connected to the block. It will be fixed shortly! 👍
