### ISSUE TITLE
Rename the Code block to something closest to reality

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#245]
**Description:** a block to fire events to parent window. This can be done with `Code` block right now, but will become easier to integrate on websites if a exclusive block is used.

**Comment by baptisteArno** [comment]
Like you said, it can be done with Code block. I'm not sure what value would bring a "Fire event" block?

**Comment by erickriva** [comment]
The bot builder is mostly based on put blocks in the right place, and I can see a non-developer person using it;
Remember a piece of code, or understanding it enough to know how to change it, for a non-developer person is harder, so it difficults a 'basic' operation for them;

**Comment by Jorgelig** [comment]
@erickriva I understand that you are looking at this functionality because of the UX issue for non-technical users, but if we are talking about events between windows, I doubt that a non-technical user would implement something like that.

But I want to better understand your situation, could you share an example where you are seeing this need and how you are implementing it?

**Comment by baptisteArno** [comment]
We could maybe rename "Code" with another name then? "Script" maybe?

**Comment by baptisteArno** [comment]
Yeah, I think the name and the icon is misleading. I had users asking me if they could implement custom blocks with the code block.

I'll change the name to Script and maybe change the logo 👌

**Comment by baptisteArno** [comment]
<img width="342" alt="CleanShot 2023-01-27 at 15 55 55@2x" src="https://user-images.githubusercontent.com/16015833/215116749-935cdeab-c7e5-47e4-9515-77f6390e632a.png">

I think it's better 👍
