### ISSUE TITLE
Highlight JS code errors in `CodeEditor`

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#352]
Variables injection is working fine, but the code itself is not executed.

![image](https://user-images.githubusercontent.com/2746558/222489692-84304d2d-13a5-4725-9d8c-eb5fa58bfd19.png)
![image](https://user-images.githubusercontent.com/2746558/222490057-e73ee7b2-b53a-43b7-aae7-1a74ad622194.png)
![image](https://user-images.githubusercontent.com/2746558/222490671-afc82d43-1217-4515-ae32-456ba6cdf17a.png)

**Comment by erickriva** [comment]
It was an error in my code, an additional `)` in `foundIndex` declaration 🤡.
There is no way to warn this type of errors inside the block?

**Comment by b4s36t4** [comment]
@baptisteArno After some research and googling I found these 3 plausible solutions

1. By default codemirror doesn't have any linting available (ex: codepen.io) which doesn't throw any error. But codemirror does provide a linter package which we can leverage to parse the tree and return any diagnostic based on tree-parse.

2. As we're using `javascript` language extension provided by codemirror itself which does have `eslint` support embedded into it.

> We might need to work with eslint configuration for browser as eslint doesn't have built-in support for browser, although there's an example provided for that.

3. Instead of using codemirror, why can't we move to monaco-editor https://github.com/microsoft/monaco-editor. I have used monaco-editor before and it's seamless. 

> Monaco might take some-time as it's an entire removal of a package and replacing with new one, maybe we can have it as a new feature or so?

Attaching the implementation of the 1st option as mentioned above.

<img width="431" alt="Screenshot 2023-10-16 at 11 57 48 PM" src="https://github.com/baptisteArno/typebot.io/assets/59088937/b814bad8-21c9-4613-9d1a-4459cc15a969">

**Comment by b4s36t4** [comment]
Another solution is to running linters in wasm and use that to provide diagnostic.

example: https://quick-lint-js.com/ https://quick-lint-js.com/demo/

like we have boimejs which does have wasm lib to provide linting.

**Comment by b4s36t4** [comment]
https://github.com/biomejs/biome/blob/main/website/src/playground/CodeMirror.tsx Here is full working example for integrating biome with browser env.

**Comment by baptisteArno** [comment]
Thank you for the exploration @b4s36t4. I guess option 1 would be enough? The idea is to only catch syntax issues.

If you hover on it, does it display a helper tooltip?

**Comment by baptisteArno** [comment]
That's fine with me! 👍

**Comment by b4s36t4** [comment]
Cool, will raise PR soon.

**Comment by b4s36t4** [comment]
@baptisteArno Please check the PR #943

**Comment by baptisteArno** [comment]
This is not possible due to variable templating not being valid JS syntax
