### ISSUE TITLE
Phone input auto focus after select does not work on iOS

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#376]

**Comment by baptisteArno** [comment]
I'm not sure how to fix this. Another phone component lib has the same issue: https://gitlab.com/catamphetamine/react-phone-number-input/-/issues/173

**Comment by prateekkalra** [comment]
Hi @baptisteArno Could you please describe the issue?
How can I reproduce it?

**Comment by baptisteArno** [comment]
See the issue here: https://gitlab.com/catamphetamine/react-phone-number-input/-/issues/173

I've recorded a video

**Comment by prateekkalra** [comment]
@baptisteArno Did a lot of research on this issue. This seems to be an iphone safari specific issue. So iOS doesn't allow to programmatically focus/click on an input through onChange. It works well inside an onClick(Since it thinks user has clicked).
I tried a lot of hacks as well by using onClicks, but the Safari select dropdown doesn't render the options inside the body, so that couldn't be triggered by onClick. 
Best we can do now to disable input focusing on iphone's safari specifically, so this weird keyboard closing behavior doesn't show up. Let me know if that needs to be done?

**Comment by baptisteArno** [comment]
Closing this as it's not really important.
