### ISSUE TITLE
Ability to have conditional buttons

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#422]
![image](https://user-images.githubusercontent.com/73610779/227388960-4c10eb97-c2f6-4671-b55b-cd2bb8b2de85.png)
For example, if the user has clicked button 1, they cannot click button 4, etc.
It would be useful to have conditional buttons.

**Comment by baptisteArno** [comment]
Won't implement this because:
- I don't know how to do that properly in terms of user experience. I think it would impact the UX
- I don't really see the point of that feature. Why would you force a user not to select 2 different choices? At some point you have to "trust" your user intelligence you know! In your case I don't think the user would ever choose "Prod" and "N/A" 😅
