### ISSUE TITLE
Addressing Bad Gateway Issues with Typebot and Traefik - Need to Force Listen on 0.0.0.0

### ISSUE THREAD

**Issue by aitorroma** [baptisteArno/typebot.io#911]
Hello, guys

We have recently been experiencing issues with typebot running with traefik.

Suddenly, it has started showing bad gateway issues; the service seems to be listening but on the internal IP of the container.

builder_1 | - Local: http://24a710abee4f:3000/
builder_1 | - Network: http://192.168.0.4:3000/

Do you know if there is a way to force it to listen on 0.0.0.0?

I believe this will solve the problem; I have encountered similar issues with other dockers in the past, and forcing listening on all interfaces manages to solve the problem.

Regards,

**Comment by baptisteArno** [comment]
I'm really not an expert here. It just stopped working as expected without doing anything?

**Comment by Chukowski** [comment]
Hello, I have the same problem with the last updated( Im using docker) first it gave me an error in the builder(when previewing the bots) 
Then went to compose down and up to see if solve anything but then I got a bad gateway so I reverted it back to the previous version and it worked, I did the update again just in case and then again got the error.

**Comment by hectoreguzmanc** [comment]
Hello, I have the same problem with Bad Gateway

But in the part of the bots in production, in the constructor I can work

Attachment screenshot

![Captura de pantalla 2023-10-12 084705](https://github.com/baptisteArno/typebot.io/assets/112967245/16b8eb3c-4fbd-49d6-b749-08e29df2805f)
![Captura de pantalla 2023-10-12 084813](https://github.com/baptisteArno/typebot.io/assets/112967245/80e3fb0a-8dc3-44bb-8d39-8c41ae32c0e0)

**Comment by baptisteArno** [comment]
I can't guess the issue guys, I need more information, your docker-compose files and your docker-compose logs would help a lot :)

**Comment by rmarquess** [comment]
After the update it shows two local networks and the internal docker network. Traefik cannot communicate with the container network for some reason.

![two-networks](https://github.com/baptisteArno/typebot.io/assets/23084429/1536cccf-184e-4944-88a1-5ea82051ca1f)

In the Traefik logs it appears as a connection refused, however the container runs normally and does not present any errors.

![connection refused](https://github.com/baptisteArno/typebot.io/assets/23084429/ab252df4-c7e5-4721-8d63-91ae1f9c3192)

I noticed that in this update 2.18.1 two networks appear, I don't know if that's exactly the problem because of that.

In version 2.18.0 there is no such problem, but I also noticed that in the typebot log only one network appears.

![typebot-antes-da-atualizacao](https://github.com/baptisteArno/typebot.io/assets/23084429/250149c3-cda0-4712-b072-de8917f7f88b)

Before this update there was no conflict with Traefik and other applications run normally.

![traefik typebot](https://github.com/baptisteArno/typebot.io/assets/23084429/ee20ccac-2a36-4975-99a4-f20b1da666ee)

I tried to give as much example as possible, I'm not a dev and maybe I can help you understand.

**Comment by aitorroma** [comment]
Hello, if you force the daemom to listen at 0.0.0.0 that is *:3000 the problem should be solved, Trafik gives some problems when it listens to the internal IP because I think it tries to make the connection at localhost:3000 if you allow it to listen at *: 3000 should solve the problem.  Is there any way to force it?  If so, we could try the workarround.  in version 2.18.0 it does not happen.

**Comment by nebulade** [comment]
We also hit this issue, although in our case it seems to be related to nodejs version >=17 preferring ipv6 interfaces as the default to listen on. So maybe this is not specific to typebot. I wasn't able to find a config option for nodejs itself to control this behavior without changing the code itself. I guess we need some env variable or such to be able to explicitly specify `0.0.0.0` for a `server.listen()` https://github.com/nodejs/node/issues/40537

**Comment by baptisteArno** [comment]
Ok so this is most likely related to Next.js upgrade to `13.5.4`. I'll investigate and let you know

**Comment by baptisteArno** [comment]
Releasing a potential fix on v2.18.2 (https://github.com/baptisteArno/typebot.io/actions/runs/6508587812). Hopefully this works 🤞

**Comment by nebulade** [comment]
I can confirm that exposing `HOSTNAME=0.0.0.0` in the runtime environment is picked up correctly. We also found that adding [--dns-result-order=ipv4first](https://nodejs.org/api/cli.html#--dns-result-orderorder) as a nodejs generic argument works, but I prefer `HOSTNAME` is better as more explicit.

**Comment by aitorroma** [comment]
Thanks, its works!

**Comment by rmarquess** [comment]
Thanks @baptisteArno, now everything is working!

**Comment by Juanmi18** [comment]
> I can confirm that exposing `HOSTNAME=0.0.0.0` in the runtime environment is picked up correctly. We also found that adding [--dns-result-order=ipv4first](https://nodejs.org/api/cli.html#--dns-result-orderorder) as a nodejs generic argument works, but I prefer `HOSTNAME` is better as more explicit.

Yes!!! It's works 

Thanks!!!!
